Order layers and legend panel by xml, index or toplayer
geobretagne/mviewer pull request #407
Opened 2020-11-02 15:16 UTC by Gaetanbrl

Actions nécessaires avant merge : 

* Documentation générale et du nouveau paramètre
* Review
* Tests

2020-11-02 15:29 UTC, Gaetanbrl commented on index.html
> +                filter: '.toplayer',
Permet d'être certain qu'un élément de la liste ne peut être déplacé selon la doc :
`  filter: ".ignore-elements", // Selectors that do not lead to dragging (String or Function)`

 https://github.com/SortableJS/sortablejs

2020-11-02 15:29 UTC, Gaetanbrl commented on js/configuration.js
> +                    oLayer.index = layer.index ? parseFloat(layer.index): null;
A ajouter dans la doc.

2020-11-02 15:29 UTC, Gaetanbrl commented on js/configuration.js
> +        getIndexByLayers: _getIndexByLayers,
Méthodes à nettoyer.

2020-11-03 08:11 UTC, spelhate commented on js/mviewer.js
> +                var layer = mviewer.getMapLayer(id);
Pourquoi un simple `mviewer.getLayer(id).layer` ne suffirait-il pas plutôt que de créer une nouvelle méthode getMapLayer ?

2020-11-03 08:17 UTC, Gaetanbrl commented on js/mviewer.js
> +                var layer = mviewer.getMapLayer(id);
J'avais complètement oublié cette méthode...merci

2020-11-03 08:21 UTC, Gaetanbrl commented on js/mviewer.js
> +            var ids = Object.keys(layersIndex);
En l'état j'ai testé dans un xml avec 2 couches sur 4 détenant le paramètre et un autre test sans aucun `index`.
Si nous n'avons pas d'attribut pour les couches la méthode `getLayersAttribute `retourne : 

```
{bief: null
lycee: null
pnr: null}
```

Donc pas de de plantage avec `Object.keys(layersIndex);`

C'est le Array.filter qui va faire le test ensuite si nous n'avons rien (que des nulls) :

`if(!ids.filter(id => layersIndex[id]).length) return;`
 

Tu as constaté un plantage avec un autre test ?

2020-11-03 08:58 UTC, Gaetanbrl commented on js/configuration.js
> +                    oLayer.index = layer.index ? parseFloat(layer.index): null;
Doc modifiée.

2020-11-03 16:01 UTC, spelhate approved these changes

2020-11-03 16:02 UTC, spelhate commented
Je vais tester avec différentes configurations

2020-11-03 17:07 UTC, spelhate requested changes
J'ai un plantage de la fonction orderTopLayer avec la configuration mviewer apps/default.xml
La couche epci n'est plus visible sur la carte.

2020-11-04 07:35 UTC, Gaetanbrl commented
> J'ai un plantage de la fonction orderTopLayer avec la configuration mviewer apps/default.xml

OK @spelhate  je vais regarder

2020-11-04 07:50 UTC, Gaetanbrl commented
@spelhate  le soucis provient des groupes de couche. Je vais adapter la PR.

2020-11-05 08:32 UTC, Gaetanbrl commented
> @spelhate le soucis provient des groupes de couche. Je vais adapter la PR.

Quand j'aurai le temps, semaine prochaine je pense.

2020-11-13 15:20 UTC, Gaetanbrl commented
3 éléments corrigés : 
* Rajouter la position des baselayers pour passer les couches au dessus
* Prendre en compte le nombre de layers groupées
* Bien inverser la liste des topLayers pour prendre en compte l'ordre dans le config.xml (la layer en bas à prendre en compte en premier pour empiler par dessus les topLayers au dessus)

@spelhate je veux bien une revues / test supplémentaire. Merci :)

2020-11-19 14:28 UTC, Gaetanbrl commented
désolé fausse manip sur la fermeture / ouverture de la PR.

2020-11-19 16:03 UTC, spelhate commented
Ok. Je regarde ça début de semaine prochaine.

2020-11-25 09:07 UTC, frgis commented
Bonjour,

pouvez-vous m'indiquer si la gestion de l'ordre des couches est gérée dans la dernière version publiée au mois de novembre (je me heurte à ce problème en ce moment) ?

Merci pour votre retour.

2020-11-25 09:09 UTC, Gaetanbrl commented
@frgis la PR étant ouverte, toutes les modifications relatives à cette PR sont encore en phase de test - correction.
Donc l'ordre des couches par numéro n'est pas encore dans la version 3.4.x.

2020-11-25 09:16 UTC, spelhate commented
Pour info, c'est en cours de test de mon côté.

2020-11-25 09:18 UTC, Gaetanbrl commented
Pas de soucis @spelhate je m'attends à avoir encore des aller-retours selon les cas.

2020-11-25 09:24 UTC, frgis commented
ok, merci pour votre réactivité.
J'ai effectivement un problème aujourd'hui car j'affiche les routes à partir d'un layer et pas d'un baselayer (peux pas afficher la photo aérienne ainsi que les routes de l'ign dans un seul baselayer et je ne peux pas non plus activer deux baselayer pour avoir photo aérienne et route). Je ne sais pas comment ça fonctionne mais les routes sont au-dessus de tous les objets ce qui masque les points d'apport volontaire partiellement.

Ca va être une belle amélioration !
Vous avez une idée de quand cela pourra être en production (avant fin d'année ou plus tard) ?

2020-11-25 09:25 UTC, spelhate commented
@Gaetanbrl peux-tu proposer une config.xml avec les paramètres qui vont bien pour favoriser les tests ? Merci.

2020-11-25 09:26 UTC, Gaetanbrl commented
ok @spelhate dès que j'ai un moment (d'ici vendredi).

2020-11-25 09:28 UTC, Gaetanbrl commented
> Vous avez une idée de quand cela pourra être en production (avant fin d'année ou plus tard) ?

@frgis ca dépendra bien entendu de nos disponibilités mais je pense qu'il peut y en avoir pour 2 semaines selon la complexité des problèmes relevés pendant les tests.

2020-11-25 10:19 UTC, spelhate commented
> ok, merci pour votre réactivité.
> J'ai effectivement un problème aujourd'hui car j'affiche les routes à partir d'un layer et pas d'un baselayer (peux pas afficher la photo aérienne ainsi que les routes de l'ign dans un seul baselayer et je ne peux pas non plus activer deux baselayer pour avoir photo aérienne et route). Je ne sais pas comment ça fonctionne mais les routes sont au-dessus de tous les objets ce qui masque les points d'apport volontaire partiellement.
> 
> Ca va être une belle amélioration !
> Vous avez une idée de quand cela pourra être en production (avant fin d'année ou plus tard) ?

En attendant une mise à jour, vous pouvez toujours réorganiser l'ordre des couches dans mviewer en glissant/déposant depuis la légende la couche que vous souhaiter mettre sur le dessus ou en dessous.

2020-11-25 11:05 UTC, frgis commented
@spelhate oui je me suis aperçu qu'il y a cette possibilité mais la carte va être intégrée dans une page web en iframe et on ne verra la légende uniquement quand on clic sur plein écran.
Ce type de carte n'est pas destiné à de l'exploration de contenus, l'idée c'est aller le plus vite possible et donc avec un minimum de clic à l'information, autrement dit un zoom, un clic.

2020-11-25 11:18 UTC, Gaetanbrl commented
@frgis peut-être qu'un autre moyen de contournement proposé par un utilisateur peut vous aider. Ce moyen est d'utiliser dans l'URL le paramètre permettant de préciser les layers à voir sur la carte.
Si vous précisez toutes vos layers à voir dans un ordre précis dans l'URL, alors c'est cet ordre qui sera pris en compte.

### Exemple : 

[https://kartenn.region-bretagne.fr/kartoviz/?l=port,commune&lb=positron&config=apps/default.xml#
](https://kartenn.region-bretagne.fr/kartoviz/?l=port,commune&lb=positron&config=apps/default.xml#
)

_On retrouve les paramètres suivants :_ 

`l` => Liste des couches
`lb` => baselayer
`config` => votre config mviewer

2020-11-25 13:11 UTC, frgis commented
Merci, c'est un contournement mais ça répond à ma problématique.
Cool !
Du coup, c'est pas embêtant actuellement en ce qui me concerne.

2020-11-25 15:55 UTC, Gaetanbrl commented
> @Gaetanbrl peux-tu proposer une config.xml avec les paramètres qui vont bien pour favoriser les tests ? Merci.

Au final @spelhate  j'utilise la config default.xml, rien d'autre pour mes tests. Après il faut ajouter les paramètres toplayer et index selon tes tests.

2020-11-25 16:28 UTC, spelhate commented
@Gaetanbrl J'ai déjà testé default.xml, ce qui m'intéresse c'est d'avoir une config qui a justifié cette évolution.
Là je ne sais trop quoi faire avec ces 2 nouveaux paramètres.  Tu me conseilles quoi ? Une conf où tous les indexs sont renseignés ? avec ou sans top layers ? combien de tops layers ?

2020-11-25 16:35 UTC, Gaetanbrl commented
> Tu me conseilles quoi ? Une conf où tous les indexs sont renseignés ? avec ou sans top layers ? combien de tops layers ?

Voici les cas de tests:

* Appliquer un index sur toutes les couches > vérifier l'ordre selon l'index (carte et légende)
* Appliquer un index sur certaines couches > vérifier que les layers avec index sont bien positionnées (carte et légende)
* Appliquer un toplayer > Vérifier qu'il est bien placé (carte et légende)
* Appliquer deux ou plus toplayer  > Vérifier qu'ils sont bien placés (carte et légende)
* Appliquer un toplayer et un ou plusieurs index > Vérifier que le top layer est en haut et que les layers sont bien placés (carte et légende)
* Ne rien ajouter (aucun toplayer aucun index) > Vérifier que les layers sont dans l'ordre du config.xml

Pour tous ces cas je ne peux pas fournir un XML standard, c'est pour cela que j'utilise des XML déjà existants et que j'ajoute les paramètres manuellement.

2020-11-25 16:41 UTC, spelhate commented
Merci @Gaetanbrl . Je poursuis demain.

2020-12-14 15:21 UTC, Gaetanbrl commented
@spelhate as tu pu tester cette PR depuis ?

2020-12-14 15:40 UTC, spelhate commented
Non pas depuis a fois dernière. Je m'y remets dès que possible.

2020-12-16 07:32 UTC, spelhate commented
Salut.
Mes  quelques tests réalisés sur la config par défaut (apps/default.xml)

**1 - Utilisation du config d'origine : pas de différence de comportement.**

**2 - Modification de default.xml --> affichage dans la config de la couche densité de population + lycées**

- comportement d'origine, la couche lycées est masquée par la couche population, la couche intercommunalité sur le haut de la pile. La légende reflète l'ordre des couches.

- Nouveau comportement. La couche intercommunalité (tooltip=true) est intercallée ebtre la couche densité de population et la couche lycée. ce qui n'est pas conforme à l'ordre des couches du xml.

**4 - Appliquer index=8 à la couche densite de population, index 0 & 1 pour les couches interco et communes, index de 3 à 7 chronologiquement pour les autres couches**

- Ok au démarrage.
- suppression de toutes  les couches --> puis affichage de lycées puis population. La couche lycée (index 3) est sous la couche population index (8) et donc invisible et ne respecte pas la priorité d'affichage.  La couche interco s'affiche bien sur le dessus de la pile (index=0)

Question : une couche qui doit s'afficher sur le haut de la carte doit avoir l'index le plus petit possible ? et par conséquent une couche avec un index élevé doit se retrouver tout en bas ?

Remarques: Il n'est pas évident de faire ces tests. Je propose d'utiliser un dossier tests contenant toutes les config à tester, les configs qui valident l'évolution...

2021-01-18 08:25 UTC, Gaetanbrl commented
@spelhate je viens de pousser des **XML** de tests (à supprimer quand tout sera validé) : 


XML | Cas de test | Statut (KO/OK)
-- | -- | --
dupplicateindex.xml | Même index répété  | ?
index | Ajout d'un numéro unique (cas normal) sur chaque couche | ?
indextoplayer.xml | Index sur toutes les couches et un seul topLayer | ?
indextoplayers.xml | Index sur toutes les couches et 2 topLayer | ?
noindextoplayers.xml | Pas d'index et 2 topLayers | ?
noindextoplayers.xml | Pas d'index et un seul topLayer | ?


**Rappel du fonctionnement détaillé :** 

* Les index sont numérotés de 1 à n où 1 est la couche au dessus et 2 est la couche sous la couche 1 en visibilité
* Les couche avec le paramètre toplayer sont au dessus des couches avec / sans index
* Les couches avec un index sont au dessus des couches sans le paramètre index
* Lorsqu'on ajoute une couche sur la carte (pour la rendre visible) elle est au-dessus de toutes les autres. Ce fonctionnement n'a pas changé.
* Si une deux couches ont le même index, elles doivent apparaître l'une au dessous de l'autre dans l'ordre du XML
* Si deux couches sont en topLayer elles doivent être en haut (car topLayer) et dans l'ordre selon le XML
* Les couches sans index doivent apparaître dans l'ordre du XML


J'ai probablement oublié des cas de test, à compléter si tel est le cas.

Il conviendra de mettre `KO `ou `OK` dans la colonne statut pour valider le test que le XML doit apporter.

2021-05-19 13:25 UTC, lecault commented
On vient de faire quelques tests avec Sébastien. J'ai complété le tableau, voici les commentaires :

Dans tes xml il y a des couches utiles qui sont en visible="false" je les ai passées en visible="true" pour les tests.

**dupplicateindex.xml KO**
Si je passe en visible="true", l'ordre d'affichage n'est pas celui attendu.
Ordre prévu : 1-1-2
Ordre actuel : 1-2-1
**Il y a un soucis si un index en double**

**index.xml OK**
si on change l'ordre car dans ton fichier c'est l'ordre logique d'affichage sur mviewer.

**indextoplayer.xml OK**
En passant port en visible="true"

**indextoplayers.xml KO** 
- Il affiche Port (toplayer index=7) au dessus de Lignes ferroviaires (toplayer index=4)
- Les couches apparaissent en double
**Si 2 toplayers, les couches sont dupliquées et l'ordre d'index non respecté.**

**noindextoplayers.xml KO**

- Lignes ferroviaires bien en haut MAIS les communes sont en bas.
- Action affichage de la couche ports au dessus de la couche lignes ferroviaires qui est top layer = changement de comportement par rapport à avant.

**Si une couche a le couple index-toplayer ça va en haut, si que toplayer, elle se retrouve en bas.**

default.xml (Pas d'index défini pour les couches) = comportement comme avant attendu.
Affichage par défaut = toplayer epci

Action 1 Affichage densité de population -> pb1 la couche vient au dessus de la couche epci toplayer. = changement de comportement par rapport à avant.

Action 2 Affichage de la couche Réserves naturelles -> pb2 la couche est tout en dessous de la couche population.  = changement de comportement par rapport à avant.

BON COURAGE

2021-05-19 13:31 UTC, Gaetanbrl commented
Merci @lecault , je me pencherai dessus quand j'aurai à nouveau du temps.

Une stratégie simple serait de seulement gérer le cas du paramètre index. Le reste on laisse. Ca marche sur un mviewer déployé chez un client et ca répond à 95% du besoin ==> Ordonnancer les couches.

2021-08-25 07:33 UTC, Gaetanbrl commented
> dupplicateindex.xml KO
Si je passe en visible="true", l'ordre d'affichage n'est pas celui attendu.
Ordre prévu : 1-1-2
Ordre actuel : 1-2-1
Il y a un soucis si un index en double

Les couches avec les zindex en doublons sont positionnées à la fin. Je ne sais plus si c'était souhaité... je regarde ca.

2021-08-25 08:16 UTC, Gaetanbrl commented
>  noindextoplayers.xml KO
Lignes ferroviaires bien en haut MAIS les communes sont en bas.

@lecault quel est le comportement attendu ? Les lignes ferroviaires sont avant les communes dans le XML.

2021-08-25 09:36 UTC, Gaetanbrl commented
> Les couches apparaissent en double
Si 2 toplayers, les couches sont dupliquées et l'ordre d'index non respecté.


je ne reproduis pas les couches en doublons @lecault.

 Aussi, l'ordre d'index n'est pas respecté si 2 couches en top layers on des index respectifs. Par défaut, on prend l'ordre d'affichage dans le XML et on ordonne les top layer selon cet ordre sans prendre en compte le numéro d'index. C'est ce qu'on a du moins prévu dans le descriptif de l'issue 109, ca peut changer si vous le souhaitez ?

2021-09-17 13:27 UTC, Gaetanbrl commented
@lecault 

Est-ce possible de refaire les tests pour voir si tes retours ont été corrigés sur cette PR ?

2021-09-17 14:14 UTC, lecault commented
je commence a regarder

2021-09-17 14:21 UTC, lecault commented
est ce que je peux faire des push dans ta pr sur les XML ?

2021-09-17 14:22 UTC, Gaetanbrl commented
Pas de soucis. Pour faire des push tu dois te positionner sur la branche de travail (feature-109) et faire ce que tu veux dedans :)

2021-09-17 14:24 UTC, lecault commented
Ah c'est pas la branche pr-407 ?

2021-09-17 14:26 UTC, Gaetanbrl commented
> Ah c'est pas la branche pr-407 ?

Je ne trouve pas cette branche pr-407.
Mais GitHub en haut annonce bien que cette PR ramène la branche feature-109 vers develop.

![image](https://user-images.githubusercontent.com/16317988/133799199-061a6a06-c09a-4157-b949-c55d56f57cd5.png)

https://github.com/geobretagne/mviewer/tree/feature-109

2021-09-17 14:28 UTC, lecault commented
ok je fais joujou sur feature-109

2021-09-17 15:18 UTC, lecault commented
Rapidement mon retour. On progresse :).

dupplicateindex.xml
	=> ordre ok
	par contre si on ajoute une couche l'index ne joue plus. Mais pas forcément un soucis
	
indextoplayers.xml
	si 2 toplayers visibles au démarrage, les couches en doublons (cf commit)	
	=> BUG

noindextoplayers.xml
	ok

default.xml
	résolu

Un bug et une opération à débat.

Bon weekend

2021-09-21 07:22 UTC, Gaetanbrl commented
@lecault 

> par contre si on ajoute une couche l'index ne joue plus. Mais pas forcément un soucis

Ce fonctionnement actuel est conservé (trop complexe à gérer et peu gênant).

> si 2 toplayers visibles au démarrage, les couches en doublons (cf commit)

Ah je n'arrivais pas à reproduire ! Je vais regarder :)


> Un bug et une opération à débat.

C'est une synthèse de tes tests ou une remarque en plus ?

2021-09-21 07:36 UTC, lecault commented
Juste un commentaire.
Ok je te laisse regarder pour les couches en double et je referai des tests plus poussés.

2021-09-21 13:00 UTC, Gaetanbrl commented
> Ok je te laisse regarder pour les couches en double et je referai des tests plus poussés.

C'est corrigé.
Le problème survient quand on a en effet 2 `toplayer="true"` car la méthode `addLayer` qui ajoute une couche dans la légende utilise la méthode JQuery `.after()`.

Lorsqu'on utilise .after() on va demander de rajouter un élément dans le DOM après les  éléments ciblés.

Donc dans notre cas on cherche à ajouter la légende d'une couche après ce qui est ciblé comme `toplayer` :

`$("#layers-container .toplayer").after(item);`

Ce qui veut dire que `$("#layers-container .toplayer")` retourne 2 éléments html `toplayer` et que pour chacun de ces éléments, on rajoute après le HTML de la légende de la couche concernée.

Donc on ne va cibler que le dernier des élément `.toplayer` et pas tous via la méthode JQuery `.last()` ;)
# code 

https://github.com/geobretagne/mviewer/blob/5567bea3a5e1fa8ae9becd960b45e2c5b4932fe7/js/mviewer.js#L2375-L2379

2021-09-24 07:00 UTC, lecault commented
Le paramètre showintoc n'est pas pris en compte exemple ici : 
 http://localhost/mviewer/?config=apps/showintoc_toplayer.xml

Mais je crois savoir pourquoi : la PR est partie d'une branche qui n'avait pas pris en compte cette évolution.
Il me semblerai bien de tester tes dev avec ces dernières modifs. Comment procéder ?

2021-09-24 07:15 UTC, lecault commented
index.xml : pourquoi port apparaît en premier alors qu'il a un index de 7 ?Ce n'est pas normal. 
Idem dans indextoplayer.xml et indextoplayers.xml, les gares maritimes ne sont pas au bon endroit.

Sinon le reste ok

2021-09-24 07:25 UTC, Gaetanbrl commented
>  la PR est partie d'une branche qui n'avait pas pris en compte cette évolution.

oui, cette PR n'est pas à jour. Il ne semble pas y avoir de conflit pour autant mais je ferai un rebase quand tout sera OK avant de merge pour ne être certain.

2021-09-24 07:26 UTC, Gaetanbrl commented
> pourquoi port apparaît en premier alors qu'il a un index de 7 

Ma dernière modification a ajouté des régressions.

En réalité tout ce bloc n'a plus lieu d'être car ensuite mon code réorganise tout : 

https://github.com/geobretagne/mviewer/blob/5567bea3a5e1fa8ae9becd960b45e2c5b4932fe7/js/mviewer.js#L2375-L2379

2021-11-05 08:05 UTC, Agath21 approved these changes
La partie fonctionnelle a été testé, RAS - Code non revu

2021-11-05 09:54 UTC, Gaetanbrl commented
Merci @Agath21 @lecault un retour / un test ? 

Sans retour, je merge en fin de journée. L'objectif est toujours la release pour le prochain PSC.

2021-11-08 11:01 UTC, merged