Issue 390 - Fixing a tooltip shift in simplified/ultrasimplified mode
geobretagne/mviewer pull request #413
Opened 2020-11-06 08:16 UTC by cbriand

2020-11-06 08:19 UTC, Gaetanbrl commented
Merci pour la PR @cbriand

2020-11-06 08:20 UTC, Gaetanbrl reviewed
A tester ;)

@cbriand sais-tu pourquoi tu as 3 merge commits dans cette PR ?

2020-11-06 09:23 UTC, Gaetanbrl requested changes
La PR doit être faite depuis la dernière version de develop.

2020-11-10 09:25 UTC, cbriand commented
Remplacée par PR #419

2020-11-10 09:25 UTC, closed without merging

2021-11-08 13:26 UTC, Gaetanbrl commented
Je réouvre cette issue et ferme la PR qui nécessite une investigation.