#594 - Utilise un overlay ol avec coordonnées
geobretagne/mviewer pull request #595
Opened 2022-04-20 13:59 UTC by Gaetanbrl

#594

Cette PR permet d'utiliser un un overlay Openlayers pour la tooltip WFS et de ne plus utiliser les pixels mais les coordonnées de la carte pour positionner la popup.

https://openlayers.org/en/latest/apidoc/module-ol_Overlay-Overlay.html
https://openlayers.org/en/latest/examples/overlay.html

La configuration mviewer et le fonctionnement avec le config.xml restent inchangés.

2022-04-20 14:05 UTC, Gaetanbrl commented
Je vois une différence dans la couleur et l'affichage des infos : 

Avant :
![image](https://user-images.githubusercontent.com/16317988/164248737-f5285943-38b5-422b-a0b3-df0e02347860.png)

Après : 

![image](https://user-images.githubusercontent.com/16317988/164248863-33959975-55d4-40c3-995a-0664a6d258e1.png)

2022-04-20 14:44 UTC, lecault requested changes
KO pour moi. Sur le kartenn par défaut, il affiche toujours Morlaix Communauté dans la tooltip.

2022-04-20 14:46 UTC, Gaetanbrl commented
....Et là je vois que avec le template tout est set à la main dans le CSS pour refaire la même chose qu'OpenLayers avec les classe class="tooltip mv-tooltip" dans le `mviewer.templates.tooltip`.

Bon... je pense qu'on peu limiter le template mviewer.templates.tooltip au contenu du popover et pas refaire ce que fait déjà openLayers nativement. 

A moins qu'il y ait un comportement autre pour cette tooltip que pour les feature WFS ?

2022-04-20 14:47 UTC, Gaetanbrl commented
> KO pour moi. Sur le kartenn par défaut, il affiche toujours Morlaix Communauté dans la tooltip.

Je veux + de détails @lecault :)

2022-04-20 14:48 UTC, Gaetanbrl commented
j'ai reproduis @lecault

2022-04-20 15:22 UTC, Gaetanbrl commented
@lecault fixé pour le refresh des infos dans la popover (règles bootstrap qui impose de la détruire avant de la refaire).

2022-04-20 15:48 UTC, Gaetanbrl commented on js/info.js
> -        $(noTooltipZone.join(", ")).on('mouseover', function() {
Cet event est devenu inutile car un overlay n'affichera son contenu que si la souris est sur la map.

2022-04-20 15:49 UTC, Gaetanbrl commented on js/templates.js
> +        '<div class="mv-tooltip tooltip-inner popover-content"></div>',
obligatoire pour passer le template `mviewer.templates.tooltip` au popover et avoir un affichage du contenu correct.
Pas certain que tooltip-inner soit utile mais je le laisse pour éviter que des règles CSS ne soient plus appliquées.

2022-04-20 15:50 UTC, Gaetanbrl commented on js/info.js
> +            $(popup).popover({
A noter que popover est un élément Bootstrap

2022-04-21 07:32 UTC, lecault approved these changes
Ok pour moi. Test sur 2 XML avec popup

2022-04-21 07:45 UTC, Gaetanbrl commented
merci @lecault j'attends un retour de @spelhate au cas où certains effets de bord que je n'ai pas identifié existent.

2022-04-21 11:43 UTC, spelhate approved these changes
Merci @Gaetanbrl. cette évolution permet d'exploiter les capacités d'Ol6.
A noter que mviewer a été développé sur à la base avec ol3 sans refactorisation systématique du code avec l'arrivée des versions 4,5 et 6.

2022-04-21 12:12 UTC, Gaetanbrl commented
> A noter que mviewer a été développé sur à la base avec ol3 sans refactorisation systématique du code

Oui pas de soucis, le fait de repasser le code sans JQuery permettra je pense de remettre le nez dans certaines section du code.

2022-04-21 12:13 UTC, Gaetanbrl commented
@Agath21 ==> A noter pour la refacto futur du CSS ==> revoir les règles en lien aux tooltip

2022-04-21 12:14 UTC, Gaetanbrl commented
Merci les reviewers 👍 ! Je merge.

2022-04-21 12:14 UTC, merged