add download button to filter addon
geobretagne/mviewer pull request #605
Opened 2022-05-11 12:46 UTC by dds2010

PR financé par Geo2France.
Ceci permet d'ajouter des boutons de téléchargement à l'addon Filter. Si la couche est une couche WFS, les boutons permettent de télécharger les données filtrées via une requête WFS.

2022-05-12 09:17 UTC, lecault commented
Bonjour,

Merci pour cette proposition de PR que nous allons tester.

Toutefois pour les prochains développements, il est d'usage de partager vos demandes d'évolutions à la communauté via l'ouverture d'une issue et du coup lancer la discussion sur les développements (voir page [contributions](https://mviewerdoc.readthedocs.io/fr/stable/doc_contrib/contrib.html#proposer-une-modification)).

Bonne journée,

2022-05-13 07:00 UTC, vfabry commented
Bonjour Loïc,
Oui tu as raison on aurait du passer par la communauté. Mais on avait une idée assez précise de notre besoin, qui était relativement urgent, d'où cette façon de faire. Promis, on s'y prendra mieux la prochaine fois !
Vincent

2022-05-13 07:15 UTC, dds2010 commented
Oui de mon coté, c'est une première contrib et c'est vrai que je n'ai vu qu'après coup le process de création passant par le ticket. Désolé, la deuxième sera plus propre ;-)

2022-05-13 14:43 UTC, dds2010 commented
Si besoin, voilà une URL pour tester la modification sur un exemple de contexte: https://dds2010.github.io/mviewer/?config=demo/filter/sinp_test_filter.xml#

2022-05-20 08:31 UTC, Gaetanbrl commented
> Si besoin, voilà une URL

Merci, je vérifie tout de suite la PR

2022-05-20 08:38 UTC, Gaetanbrl commented
Dans votre démo il y a la valeur "Choisissez...".
Cependant la liste des attributs "Operator" semble trop longue et plante l'utilisation du plugin. Nous n'avons pas cette valeur dans la [démo du filtre initiale](https://kartenn.region-bretagne.fr/kartoviz/?config=demo/filter/filter.xml).

![image](https://user-images.githubusercontent.com/16317988/169489159-c5a49e69-bb59-48dd-94de-3017c6d8f489.png)

2022-05-20 08:39 UTC, Gaetanbrl commented
Pour l'affichage des formats, j'aurai préféré une liste plutôt qu'un affichage textuel des valeurs.

![image](https://user-images.githubusercontent.com/16317988/169489538-5419a95a-0f30-4499-86de-cd6ad5114eaf.png)


@Agath21 tu en penses quoi ?

2022-05-20 09:10 UTC, Gaetanbrl requested changes
Plusieurs éléments à voir : 

1. Le code style JS et XML avec une uniformisation des espaces, sauts de lignes et indentations (utiliser jsbeautifier si besoin)
2. Nettoyer les console.log indésirables (on en a pas besoin en dehors des devs)
3. Je ne suis pas certain que l'affichage dans un span est idéla (un <a> avec href serait plus simlple à créer pour le bouton du format)
4. Je me demande si l'affichage dans le panel est le mieux, une liste dans le footer serait plus simple ?
5. Problème de scroll avec une liste d'attributs trop longue. Mais c'était peut-être déjà là avant la PR

2022-05-20 09:10 UTC, Gaetanbrl commented on demo/addons/filter/js/filter.js
> +          url+=_getFilter(layerConfig.layerId);
Je pense que ce serait plus simple de laisser le choix du label dans la config.

On aurait donc dans la config.json le format et le label : 

```
"downloadFormats": [
    { label: "CSV", format: "CSV" },
    { label: "Shapefiles", format: "SHAPE-ZIP" },
    { label: "Geojson", format: "application/json" }
];
```

Ca permet de rajouter facilement un autre format de téléchargement supportépar le serveur carto et ca donne la main sur le label.

C'est aussi plus simple pour la création du bouton.

2022-05-20 12:27 UTC, dds2010 commented
Super, Merci pour ces retours, je vais apporter les modifications demandées sur les aspects techniques. 
Pour les aspects présentation ( utilisation d'un footer, liste ou boutons ), je laisse @vfabry réagir

2022-05-20 12:28 UTC, dds2010 commented on demo/addons/filter/js/filter.js
> +          url+=_getFilter(layerConfig.layerId);
Oui bonne idée, je vais modifier ça

2022-05-20 12:40 UTC, smevel commented on demo/addons/filter/js/filter.js
> +          url+=_getFilter(layerConfig.layerId);
> Je pense que ce serait plus simple de laisser le choix du label dans la config.
> 
> On aurait donc dans la config.json le format et le label :
> 
> ```
> "downloadFormats": [
>     { label: "CSV", format: "CSV" },
>     { label: "Shapefiles", format: "SHAPE-ZIP" },
>     { label: "Geojson", format: "application/json" }
> ];

+1 je rajouterai le format geopackage qui est pris en charge par geoserver

2022-05-20 13:58 UTC, dds2010 commented on demo/addons/filter/js/filter.js
> +      if(layerConfig.downloadFormats && layerConfig.downloadFormats.length>0)
ok fait

2022-05-20 13:59 UTC, dds2010 commented on demo/filter/sinp_test_filter.xml
> +				</layer>
ok fait

2022-05-20 14:00 UTC, dds2010 commented
voilà j'ai commité les changements techniques. A discuter pour le fonctionnel

2022-05-20 14:04 UTC, dds2010 commented
> Plusieurs éléments à voir :
> 
>     1. Le code style JS et XML avec une uniformisation des espaces, sauts de lignes et indentations (utiliser jsbeautifier si besoin)
> 
>     2. Nettoyer les console.log indésirables (on en a pas besoin en dehors des devs)
> 
>     3. Je ne suis pas certain que l'affichage dans un span est idéla (un  avec href serait plus simlple à créer pour le bouton du format)
> 
>     4. Je me demande si l'affichage dans le panel est le mieux, une liste dans le footer serait plus simple ?
> 
>     5. Problème de scroll avec une liste d'attributs trop longue. Mais c'était peut-être déjà là avant la PR

* 1 et 2 fait
* 3 : on peut sans doute faire mieux, le span m'allait bien pour aller vite sur le css
* 4 : a voir avec @vfabry 
* 5 : oui ce n'est pas lié aux modifs je pense

2022-05-24 15:25 UTC, vfabry commented
Pour le point 3 : le text (plutôt qu'un bouton) me va bien, en tout cas dans le budget et le temps imparti ça colle bien avec notre demande.
Pour le point 4 : l'affichage dans le panel me va bien, je trouve que fonctionnellement ça prolonge bien l'idée du filtre : 
1- je filtre les données
2- je télécharge dans la foulée le résultat de mon filtre

2022-06-03 13:21 UTC, dds2010 commented
hello, désolé de mon coté il me semble que tout est traité. 
Est ce qu'il reste des choses en suspend, je n'ai pas bien compris s'il fallait modifier les boutons?

2022-06-03 13:45 UTC, Gaetanbrl commented
Même si j'aurai préféré une autre approche avec les boutons et la config (qui aurait été discuté avant le lancement des développements via la création d'une issue) c'est bon pour car c'est une fonctionnalité qu'on peut masquer si non désirée.

Une évolution sera à prévoir pour prendre en compte nos retours (donc du temps à passer pour quelqu'un, un jour).

2022-06-03 13:45 UTC, Gaetanbrl approved these changes

2022-06-09 10:08 UTC, lecault commented
Fonctionnalité intéressante, il me semblerait bien  d'ajouter cette fonctionnalité dans la documentation https://mviewerdoc.readthedocs.io/fr/latest/doc_tech/config_extensions.html.

@Gaetanbrl tu l'as testé avec une autre source ?

2022-06-09 10:19 UTC, Gaetanbrl commented
non pas testé avec une autre source.

2022-06-09 10:20 UTC, Gaetanbrl commented
@dds2010 tu peux rajouter cette fonctionnalité dans la doc ?

2022-06-09 13:29 UTC, dds2010 commented
ok je l'intègre dans la PR

2022-06-09 14:43 UTC, lecault commented
Je teste avec une autre donnée et je te redis

2022-06-10 07:24 UTC, Gaetanbrl commented
> Il y aurait t'il des préconisations au niveau du js ?

Je viens de tester et je n'avais pas pensé à ce cas d'usage en regardant le code.
Cette fonctionnalité ne peut pas fonctionner avec des custom layer car les téléchargements se font via les URLs WFS...
En l'état ca provoque une erreur.

Il faudrait le préciser dans la doc ou compléter avec un export JSON ou CSV pour les données d'un customlayer.
Mais dans le cas du plugin FIlter du répertoire /demo ca ne sert pas à grand chose car le custom layer est déjà founi via un fichier plat.

Donc on ne devrait pas pouvoir voir les boutons si le fichier a été chargé en local :

- `mviewer.getLayer("commune").url` =>  `demo/filter/customlayers/communes.js`
- `mviewer.getLayer("commune").layer.getSource().getUrl()` => `data/commune_simple.geojson`

Désolé, @dds2010 il manque un test pour masquer les liens si c'est un custom layer je n'aurai pas du approuver en l'état.

2022-06-10 07:24 UTC, Gaetanbrl requested changes
Ajouter un contrôle pour un custom layer via un fichier local.

2022-06-10 09:54 UTC, dds2010 commented
J'ai indiqué dans la doc que ça ne marchait que pour des WFS, je ne sais pas s'il faut rajouter un contrôle en plus dans le code. Je veux bien  mais ça me semble pas utile: si le téléchargement n'est pas possible il ne faut pas rajouter l'option  downloadFormats non ?

2022-06-10 10:06 UTC, Gaetanbrl commented
> si le téléchargement n'est pas possible il ne faut pas rajouter l'option downloadFormats non

Oui mais c'est une logique de développeur qui connaît bien le paramétrage et ce n'est pas le cas de ceux qui vont tester le plugin ou qui ne sont pas forcément à l'aise avec les extensions (qui débutent).

Pour la qualité de code et le confort de l'utilisation une gestion d'erreur + un petit message (alert bootstrap) serait le bienvenu.

2022-06-10 10:47 UTC, dds2010 commented
ok j'ai rajouté un message pour les layers qui ont des urls locale. 
Bon en fait ça ne me semble pas super car ça va bloquer les urls de type /geoserver/wfs. Difficile de détecter si une url concerne un flux WFS ou un fichier local

2022-06-10 10:50 UTC, dds2010 commented
J'ai aussi corrigé le problème sur le test avec "https://geobretagne.fr/geoserver/livre_lecture/wfs?SERVICE=WFS&VERSION=1.0.0&REQUEST=GETFEATURE&TYPENAME=reseau&outputFormat=application/json&srsName=EPSG:4326"
Effectivement dans mes tests j'étais passé par une fonction pour configurer la couche WFS mais je viens de traiter le cas ou c'est une URL simple comme dans le cas indiqué par @lecault :
```
mviewer.customLayers.occurence_public_filter.layer = new ol.layer.Vector({

	source: new ol.source.Vector({
		url: function (extent) {
			if(extent){
				return (
					'https://magosm.magellium.com/geoserver/wfs?service=WFS&' +
					'version=1.1.0&request=GetFeature&typename=magosm:france_telecom_fibre_connection_point&' +
					'outputFormat=application/json&srsname=EPSG:3857&' +
					'bbox=' +
					extent.join(',') +
					',EPSG:3857'
				  );
			}else{
				return (
					'https://magosm.magellium.com/geoserver/wfs?service=WFS&' +
					'version=1.1.0&request=GetFeature&typename=magosm:france_telecom_fibre_connection_point&' +
					'srsname=EPSG:3857&'
				  );
			}
			
		},
		strategy: ol.loadingstrategy.bbox,
		format: new ol.
```

2022-06-10 13:03 UTC, lecault commented
Je confirme le problème est résolu, merci @dds2010

2022-06-10 15:14 UTC, Gaetanbrl commented
> ok j'ai rajouté un message pour les layers qui ont des urls locale.

Je vois pas dans le test de la PR.

On par contre plus l'erreur au démarrage mais au clic.
Je pense que si c'est galère :
1. On affiche une alerte (avec un try except pour la gestion de l'erreur ca évite de se prendre la tête)
2. On se suffit de la doc pour indiquer que ca marche pas avec les fichiers locaux

2022-06-10 15:51 UTC, dds2010 commented
j'ai mis un test ici 
https://github.com/geobretagne/mviewer/pull/605/files#diff-1f605aefb4bd62881d6e712cc6a494fe9416055713d356e676dff73e31bb571cR212

2022-06-13 07:19 UTC, Gaetanbrl requested changes

2022-06-13 07:19 UTC, Gaetanbrl commented on demo/addons/filter/js/filter.js
> +        if (url.apply || url.indexOf('http')==0) {
Ne peux pas fonctionner si on appel un fichier JSON externe (ex: open data).

2022-06-13 07:19 UTC, Gaetanbrl commented on demo/addons/filter/js/filter.js
> +        if (url.apply || url.indexOf('http')==0) {
Je pense toujours qu'un try catch ferait le travail...

https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Statements/try...catch

2022-06-13 07:21 UTC, Gaetanbrl commented on demo/addons/filter/js/filter.js
> +        if (url.apply || url.indexOf('http')==0) {
```
try {
  _addDownLoadPanel(destinationDivId, layerConfig);
} catch (error) {
   mviewer.alert("L'option downloadFormats ne fonctionne qu'avec des couches WFS", "alert-info")
   console.error("L'option downloadFormats ne fonctionne qu'avec des couches WFS")
}
```

2022-06-13 09:37 UTC, dds2010 commented on demo/addons/filter/js/filter.js
> +        if (url.apply || url.indexOf('http')==0) {
ok c'est modifié avec un try catch

2022-06-13 12:40 UTC, Gaetanbrl commented on demo/addons/filter/js/filter.js
> +        if (url.apply || url.indexOf('http')==0) {
top merci ! je reteste

2022-06-13 12:49 UTC, Gaetanbrl requested changes

2022-06-13 16:16 UTC, Gaetanbrl commented on demo/addons/filter/js/filter.js
> +    window.open(url, "target='_blank'")
> je n'ai peut être pas bien compris mais pour traiter le cas de @lecault avec le flux

Le cas que je met en avant c'est la lecture d'un fichier local dans le répertoire mviewer/ (c'est une ressource mviewer classique .json avec un custom layer qui lit un fichier local et qui n'utilise pas de flux OGC).

En tout il faut gérer ces 3 cas : 

1. Couche via appel WMS ==> Cas nominal de la PR
2. Couche via appel WFS ==> Cas de Loïc
3. Couche via un fichier JSON (custom layer et chemin relatif ou absolu si JSON récupéré en externe) ==> Cas que je test

2022-06-13 16:20 UTC, Gaetanbrl commented on demo/addons/filter/js/filter.js
> +    window.open(url, "target='_blank'")
> On est dans dans le cas ou url n'est pas une fonction mais on peut quand même y rajouter les filtres

Du coup en effet il faut garder les filtres et prévoir une autre condition... je n'avais pas pensé au CQL WFS

2022-06-13 16:25 UTC, Gaetanbrl commented on demo/addons/filter/js/filter.js
> +    window.open(url, "target='_blank'")
Aussi pour manipuler les URLs et les params y a aussi des trucs plus souples qu'une regex avec l'[API web URL](https://developer.mozilla.org/fr/docs/Web/API/URL) en JS mais en l'état ca me va.

2022-06-13 17:05 UTC, Gaetanbrl commented
@dds2010 je viens de voir que le window.open génère une erreur quand on sélectionne pour sinp une couleur ou un opérateur.
On a alors cette url et une erreur CQL même si le CSV est téléchargé.

En général on a plutôt cette manière de télécharger un CSV / JSON : 

https://stackoverflow.com/questions/14964035/how-to-export-javascript-array-info-to-csv-on-client-side

2022-06-13 17:07 UTC, Gaetanbrl commented on demo/addons/filter/js/filter.js
> +    window.open(url, "target='_blank'")
En faisant comme ca ca marche pas mal dans mes tests : 

```
  var _download = function(layerConfig, format) {
    var url = mviewer.getLayer(layerConfig.layerId).layer.getSource().getUrl()
    var parseURL = new URLSearchParams(url);
    
    if(url.apply){ // Si getUrl() renvoie une fonction
      url = mviewer.getLayer(layerConfig.layerId).layer.getSource().getUrl().apply(null, []);
    }
    if (format.format) {
      // manage format and replace if already exists - use mixed method to change outputFormat param
      url = parseURL.has("outputFormat") ? url.replace(new RegExp(/&outputFormat(.*)(&|$)/), '') : url;
      url += `&outputFormat=${format.format}`;
    }
    if (_getFilter(layerConfig.layerId)) { // add only if filters exist
      url += _getFilter(layerConfig.layerId);
    }
    window.open(url, "target='_blank'")
  }
```

2022-06-14 12:32 UTC, dds2010 commented on demo/addons/filter/js/filter.js
> +    window.open(url, "target='_blank'")
- format.format devrait être ok systématiquement à mon sens sinon c'est un pb de config mais ok. 
- URLSearchParams : j'ai l'impression que ça n'est pas supporté par IE du coup je préfère m'en passer vu que ca n'apporte pas non plus grand chose ici (https://developer.mozilla.org/fr/docs/Web/API/URLSearchParams)

Donc A voir je ne suis pas forcément ok avec ces modifs surtout pour URLSearchParams mais si ça va à @vfabry j'intègre

2022-06-14 13:39 UTC, vfabry commented
si vous voulez que je donne un avis il va falloir vulgariser parce que je suis largué, là :-)

2022-06-14 13:52 UTC, dds2010 commented
> si vous voulez que je donne un avis il va falloir vulgariser parce que je suis largué, là :-)

héhé désolé, Peut être sur le support IE, est ce qu'on fait attention à supporter internet explorer ?

2022-06-14 14:06 UTC, vfabry commented
> > si vous voulez que je donne un avis il va falloir vulgariser parce que je suis largué, là :-)
> 
> héhé désolé, Peut être sur le support IE, est ce qu'on fait attention à supporter internet explorer ?

non

2022-06-14 15:38 UTC, dds2010 commented on demo/addons/filter/js/filter.js
> +    window.open(url, "target='_blank'")
ok pas de support IE, j'ai donc intégré tes suggestions @Gaetanbrl

2022-06-14 15:44 UTC, dds2010 commented
> @dds2010 je viens de voir que le window.open génère une erreur quand on sélectionne pour sinp une couleur ou un opérateur.
> On a alors cette url GeoServer et une erreur CQL même si le CSV est téléchargé.
> `<ows:ExceptionText>Could not parse CQL filter list. Lexical error at line 1, column 9. Encountered: <EOF> after : "" Parsing : colour='.</ows:ExceptionText>`

J'essaie de reproduire le problème, avec quelle URL tu as ce problème? chez moi si je met un filtre sur operator => Orange et colour => black, j'ai une url de ce type qui fonctionne 

https://magosm.magellium.com/geoserver/wfs?service=WFS&version=1.1.0&request=GetFeature&typename=magosm:france_telecom_fibre_connection_point&srsname=EPSG:3857&&outputFormat=application/json&CQL_FILTER=operator=%27Orange%27%20AND%20colour=%27black%27

2022-06-15 06:39 UTC, Gaetanbrl commented on demo/addons/filter/js/filter.js
> +    window.open(url, "target='_blank'")
Pas besoin de support IE en effet ;)

2022-06-15 06:41 UTC, Gaetanbrl commented
> J'essaie de reproduire le problème, avec quelle URL tu as ce problème? chez moi si je met un filtre sur operator => Orange et colour => black, j'ai une url de ce type qui fonctionne

En fait je reproduis sur une couleur hexa. Les CQL sont assez chiants avec des caractères spéciaux... au pire on traitera au cas par cas selon les erreurs qu'ont peut trouver.

2022-06-15 06:48 UTC, Gaetanbrl commented
@dds2010 @vfabry @lecault je valide la PR en l'état avec une compatibilité WFS uniquement. J'aurai quelques modifications à apporter pour :
- Avoir des boutons et non des liens
- Avoir un panel avec un max height
- que ce soit compatibles avec le téléchargements des fichiers locaux (JSON avec path relatif)

2022-06-15 06:49 UTC, merged

2022-06-15 07:00 UTC, Gaetanbrl commented
merci [G2France](https://www.geo2france.fr/portail/) pour la contrib ;)

2022-06-15 08:26 UTC, lecault commented
Merci à tous pour le taf. On va préparer une release.

2022-06-16 12:50 UTC, dds2010 commented
Top, merci pour les retours et l'intégration de la PR