Issue #629 Ajouter une couche WMS à la carte
geobretagne/mviewer pull request #660
Opened 2022-09-06 15:25 UTC by dds2010

Voilà une proposition pour la nouvelle fonction d'ajout de couches à partir d'un service OGC ou CSW. 

Pour tester vous pouvez regarder ici :
https://dds2010.github.io/mviewer/?config=demo/addlayers.xml

il y a un fichier de configuration que j'ai mis dans data/ogc_csw_server.json (peut être pas au bon endroit, je le déplacerai si besoin ) et qui permet de configurer les serveurs OGC et CSW proposé dans les listes. 

Sa structure est la suivante:
```
{
"ogc":[
    {"label":"Geoserver geo2France","url":"https://www.geo2france.fr/geoserver/hdf_common/ows"},
    {"label":"QGIS Server hauts de france","url":"https://qgisserver.hautsdefrance.fr/cgi-bin/qgis_mapserv.fcgi?MAP=/var/www/data/qgis/applications/sraddet_2020_08.qgz"},
    {"label":"Mapserver GeoIDE","url":"https://ogc.geo-ide.developpement-durable.gouv.fr/wxs?map=/opt/data/carto/geoide-catalogue/1.4/org_38148/cac35f5b-fa24-442f-8297-9e9495f06f36.internet.map"},
    {"label":"Geoportail IGN","url":"https://wxs.ign.fr/ortho/geoportail/r/wms"}
],
"csw":[ 
    {
        "label":"Catalogue PIGMA",
        "url":"https://www.pigma.org/geonetwork/srv/eng/csw",
        "defaultfilter":"protocol='OGC:WMS-1.1.1-http-get-map' OR protocol='OGC:WMS'"
    },
    {"label":"Catalogue GrandLyon","url":"https://download.data.grandlyon.com/catalogue/srv/eng/csw","defaultfilter":"protocol='OGC:WMS-1.1.1-http-get-map' OR protocol='OGC:WMS'"},
    {"label":"Catalogue Geo2France","url":"https://www.geo2france.fr/geonetwork/srv/fre/csw","defaultfilter":"linkProtocol='OGC:WMS'"},
    {"label":"Catalogue GeoBretagne","url":"https://geobretagne.fr/geonetwork/srv/fre/csw","defaultfilter":"protocol='OGC:WMS-1.1.1-http-get-map' OR protocol='OGC:WMS'"} 
]
}
```

Il y a aussi une fonction qui permet d'ajouter une couche directement à la carte en passant un paramètre dans l'url.
le nouveau paramètre est **addLayer** et doit contenir en valeur un objet JSON contenant url, name et title.

J'ai hésité avec l'ajout de 3 paramètres dans l'url mais je me suis dit que ça serait plus évolutif de passer par du JSON si on veut par exemple ajouter plusieurs couches => à débattre

Un exemple ici, attention la couche ajoutée est sur les hauts de france
https://dds2010.github.io/mviewer/?config=demo/addlayers.xml&addLayer={\%22url\%22:\%22https://www.geo2france.fr/geoserver/hdf_common/ows\%22,\%22name\%22:\%22Antennes__HdF_EnService_Agreg\%22,\%22title\%22:\%22Antennes_test\%22}

j'ai refactorisé un peu le code dans configuration.js de manière à pouvoir utiliser la fonction d'ajout de couche WMS en dehors du bloc de code qui fait l'initialisation de la carte.

2022-09-06 15:46 UTC, vfabry commented
pour faire suite à cette issue : https://github.com/geobretagne/mviewer/issues/629

2022-09-12 05:55 UTC, spelhate commented
Merci pour la PR, on va regarder ça.

2022-09-26 09:07 UTC, spelhate requested changes
Bonjour @dds2010 et @vfabry  et merci pour ce travail.
J'ai effectuée une rapide revue de code et tout semble ok sauf 

- les modifications apportées aux fichiers themes/*.css car ces fichiers ont été complètement reformatés. 
-  documentation (Paramètre addLayer dans la configuration de l'application + paramètre de couche owsoptions.

2022-09-26 09:07 UTC, spelhate commented on css/themes/green.css
> +  font-family: "roboto_bold";
Il y a un soucis sur ce fichier qui en principe est généré automatiquement à partir du fichier theme.scss.
Là il apparaît comme totalement reformaté. Il faut ne faut pas intégrer dans ces commits de la mise en forme de code car ça complexifie considérablement la review.

2022-09-26 09:07 UTC, spelhate commented on css/themes/green_sea.css
> +  font-family: "roboto_bold";
Il y a un soucis sur ce fichier qui en principe est généré automatiquement à partir du fichier theme.scss.
Là il apparaît comme totalement reformaté. Il faut ne faut pas intégrer dans ces commits de la mise en forme de code car ça complexifie considérablement la review.

2022-09-26 09:07 UTC, spelhate commented on css/themes/nephritis.css
> +  font-family: "roboto_bold";
Il y a un soucis sur ce fichier qui en principe est généré automatiquement à partir du fichier theme.scss.
Là il apparaît comme totalement reformaté. Il faut ne faut pas intégrer dans ces commits de la mise en forme de code car ça complexifie considérablement la review.

2022-09-26 09:07 UTC, spelhate commented on css/themes/peter_river.css
> +  font-family: "roboto_bold";
Il y a un soucis sur ce fichier qui en principe est généré automatiquement à partir du fichier theme.scss.
Là il apparaît comme totalement reformaté. Il faut ne faut pas intégrer dans ces commits de la mise en forme de code car ça complexifie considérablement la review.

2022-09-26 09:07 UTC, spelhate commented on css/themes/pink.css
> +  font-family: "roboto_bold";
Il y a un soucis sur ce fichier qui en principe est généré automatiquement à partir du fichier theme.scss.
Là il apparaît comme totalement reformaté. Il faut ne faut pas intégrer dans ces commits de la mise en forme de code car ça complexifie considérablement la review.

2022-09-26 09:07 UTC, spelhate commented on css/themes/ripe_lemon.css
> +  font-family: "roboto_bold";
Il y a un soucis sur ce fichier qui en principe est généré automatiquement à partir du fichier theme.scss.
Là il apparaît comme totalement reformaté. Il faut ne faut pas intégrer dans ces commits de la mise en forme de code car ça complexifie considérablement la review.

2022-09-26 09:07 UTC, spelhate commented on css/themes/wet_asphalt.css
> +  font-family: "roboto_bold";
Il y a un soucis sur ce fichier qui en principe est généré automatiquement à partir du fichier theme.scss.
Là il apparaît comme totalement reformaté. Il faut ne faut pas intégrer dans ces commits de la mise en forme de code car ça complexifie considérablement la review.Il y a un soucis sur ce fichier qui en principe est généré automatiquement à partir du fichier theme.scss.
Là il apparaît comme totalement reformaté. Il faut ne faut pas intégrer dans ces commits de la mise en forme de code car ça complexifie considérablement la review.

2022-09-26 10:13 UTC, dds2010 commented on js/configuration.js
> +                    oLayer.owsoptions = layer.owsoptions;
Ce n'est pas un nouveau paramètre, il est déjà documenté dans la section "Autre Paramètres"

2022-09-26 10:22 UTC, dds2010 commented on demo/addlayers.xml
> +        addlayerstools="true"
ok c'est fait, je vais compléter aussi la doc sur les urls pour ajouter une couche. J'attendais un retour sur ma proposition de paramètres avant de documenter ça mais je vais le faire du coup.

2022-09-26 10:30 UTC, dds2010 commented on css/themes/alizarin.css
> +  font-family: "roboto_bold";
hum oui c'est bizarre, je n'ai pas reformaté ces fichiers, je pense que c'est plutôt que je ne dois pas avoir la même version de sass que vous et ça génère des différences (par exemple mon compilateur générer #ffffff au lieu de white ).

Je ne vois pas trop comment je peux régler ce problème, 2 options peut etre : 

- je ne committe pas ces fichiers
- je modifie manuellement ces fichiers pour y introduire uniquement les modifs liés à mes commits mais vous aurez certainement le soucis à la prochaine modification ou mes parties apparaitront en différence

2022-09-26 10:42 UTC, dds2010 commented on css/themes/wet_asphalt.css
> +  font-family: "roboto_bold";
ok voir 1er commentaire

2022-09-26 10:44 UTC, dds2010 commented
je cherchais dans le doc le meilleur endroit pour documenter les nouveaux paramètres d'url mais je ne vois pas. Il y a des paramètre existant qui ne sont pas documenté je pense ( &title par exemple pour changer le titre de la carte )

2022-09-26 11:46 UTC, Gaetanbrl commented on css/themes/alizarin.css
> +  font-family: "roboto_bold";
@dds2010 quel éditeur utilises-tu pour modifier les fichiers ?

2022-09-26 11:48 UTC, Gaetanbrl commented on js/configuration.js
> +                    oLayer.owsoptions = layer.owsoptions;
Je ne connaissais même pas ce paramètre (introduit par neogeo).

https://github.com/geobretagne/mviewer/issues/94

2022-09-26 11:56 UTC, Gaetanbrl commented
> Il y a des paramètre existant qui ne sont pas documenté je pense

Ce sont des paramètres à passer dans l'URL pour surcharger la config c'est cela ?

2022-09-26 12:02 UTC, spelhate commented
> 

La documentation se fait dans le répertoire **docs** de mviewer. Cette documentation est ensuite buildée par readthedocs pour ensuite être visible ici : https://mviewerdoc.readthedocs.io/fr/latest/

2022-09-26 12:03 UTC, spelhate commented on css/themes/alizarin.css
> +  font-family: "roboto_bold";
> @dds2010 quel éditeur utilises-tu pour modifier les fichiers ?

Oui si ce n'est pas trop compliqué à faire.

2022-09-26 12:10 UTC, spelhate commented on js/configuration.js
> +                    oLayer.owsoptions = layer.owsoptions;
Du coup, je ne comprends pas bien pourquoi cette ligne est ajoutée dans la PR ?

2022-09-28 07:36 UTC, dds2010 commented
> > Il y a des paramètre existant qui ne sont pas documenté je pense
> 
> Tu parles des paramètres à passer dans l'URL pour surcharger la config c'est cela ?
> 
> https://mviewerdoc.readthedocs.io/fr/stable/doc_tech/config_intro.html?highlight=url#parametres-d-url

Ah oui voilà, c'est exactement ça. Je ne cherchais pas dans la bonne section, merci

2022-09-28 07:40 UTC, dds2010 commented on css/themes/alizarin.css
> +  font-family: "roboto_bold";
> @dds2010 quel éditeur utilises-tu pour modifier les fichiers ?

J'utilise vscode mais il ne reformatte pas les fichiers que je ne modifie pas et ceux ci n'ont pas été modifiés mais générés par sass. Et puis des changement de white vers #fffff ne sont pas des modifications de formattage. 
On peut comparer nos version de sass par contre ? 

```
sass --version
1.54.4 compiled with dart2js 2.17.6
```

2022-09-28 08:40 UTC, Gaetanbrl commented on css/themes/alizarin.css
> +  font-family: "roboto_bold";
tu as installé sass comment ?

2022-09-28 08:41 UTC, Gaetanbrl commented
> Ah oui voilà, c'est exactement ça. Je ne cherchais pas dans la bonne section, merci

Perso j'utilise la recherche à partir du nom du paramètre, faut lire les résultats assez nombreux mais ca se trouve :)

2022-09-30 07:44 UTC, dds2010 commented on css/themes/alizarin.css
> +  font-family: "roboto_bold";
voilà j'ai enlevé de la PR les fichiers css

2022-09-30 08:31 UTC, dds2010 commented on js/configuration.js
> +                    oLayer.owsoptions = layer.owsoptions;
humm oui ca fait un moment que j'ai fait ça, je ne sais plus trop mais il me semble avoir complété un oubli. Un paramètre qui n'était pas propagé alors qu'il aurait du

2022-09-30 08:32 UTC, dds2010 commented on demo/addlayers.xml
> +        addlayerstools="true"
doc sur les paramètres d'urls complétée aussi

2022-10-11 16:13 UTC, dds2010 commented
J'ai reglé le conflit qu'il y avait avec develop. Pour moi tout les points sont traités. Est ce que c'est ok pour vous ?

2022-11-28 13:14 UTC, ThomasG77 commented
## Remontée 1:

Quand on ajoute une URL via le paramètre `addLayer` puis qu'on fait "Partager", l'URL ne comprend pas le paramètre `addLayer`

## Remontée 2

Il faut aussi noter qu'on a régulièrement des images coupées sur le WMS (voir PJ quand on zoome/dézoome)

![Capture](https://user-images.githubusercontent.com/642120/204286148-49fe38fb-8180-4e8f-bf34-53b625d0ea44.png)

Je ne sais pas si c'est lié à la fonctionnalité dans la PR ou un autre type de bug.

Vous trouverez l'URL vers la couche ajoutée qui est la même que dans le premier commentaire de la PR mais avec zoom direct sur la zone où la couche est ajoutée https://dds2010.github.io/mviewer/?x=439666&y=6394416&z=7&config=demo/addlayers.xml&addLayer=%7B%5C%22url%5C%22:%5C%22https://www.geo2france.fr/geoserver/hdf_common/ows%5C%22,%5C%22name%5C%22:%5C%22Antennes__HdF_EnService_Agreg%5C%22,%5C%22title%5C%22:%5C%22Antennes_test%5C%22%7D qui permettra de rapidement confirmer/infirmer ce 2nd retour

2022-11-28 13:31 UTC, pierrejego commented
Le bug d'affichage de la remonté n°2 me fait penser à un soucis de loadbalancer côté geoserver. Un des serveurs n'a pas la couche d'ou l'effet coupés.  Mais c'est a vérifier

2022-11-28 13:43 UTC, ThomasG77 commented
Point 2: semble se confirmer avec https://www.geo2france.fr/geoserver/hdf_common/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=Antennes__HdF_EnService_Agreg&STYLES=&TILED=true&WIDTH=256&HEIGHT=256&CRS=EPSG%3A3857&BBOX=939258.2035682462%2C5948635.289265556%2C1252344.2714243282%2C6261721.357121638

2022-11-28 14:06 UTC, Gaetanbrl commented
@dds2010 désolé, pas eu trop le temps de remettre le nez dans la PR. Désolé.

J'ai testé avec : 

 https://geobretagne.fr:443/geoserver/dreal_b/znieff1/ows

C'est OK fonctionnellement. Il y a même la légende pour ce serveur carto.

J'ai trois remarques **non bloquantes pour la PR** : 

- on met une couche ajoutée au dessus des top-layer. Je pense qu'on pourra facilement corriger ca avec les méthodes reorder dans mviewer.js.
-
- pour l'ergo / design je pense qu'on pourra améliorer un peu tout ca (wink @Agath21), notamment pour revoir le positionnement du volet "+ Ajouter une couche" qui devrait plutôt être en dehors de la TOC ou tout au dessus je pense.

- les légendes ne se chargent pas avec les flux de la démo, j'imagine que c'est une contrainte du serveur carto derrière. Fonctionne avec le GeoServer GeoBretagne

2022-11-28 14:10 UTC, Gaetanbrl commented
Par contre je comprend pas ce que sont les carrés à l'interrogation d'un CSW  (à droite) :

![image](https://user-images.githubusercontent.com/16317988/204298327-5312ac8a-9934-4421-a11d-8ebc0442493f.png)

2022-11-28 14:17 UTC, Gaetanbrl commented
@ThomasG77 

> Quand on ajoute une URL via le paramètre addLayer puis qu'on fait "Partager", l'URL ne comprend pas le paramètre addLayer

Je pense que c'est une feature non prévue. (@dds2010 tu confirmes ?).

De ce que j'ai compris, cette PR permet d'ajouter des couches supplémentaires : 

1. Via le bouton "Ajouter"
2. Via l'URL 

Mais les couches rajoutées ne semble pas conservées lors du partage.

Je remarque par contre qu'on a un bug si on partage une carte qui contient dans l'URL une config json.

1. Ouvrir : 

https://dds2010.github.io/mviewer/?config=demo/addlayers.xml&addLayer=%7B%5C%22url%5C%22:%5C%22https://www.geo2france.fr/geoserver/hdf_common/ows%5C%22,%5C%22name%5C%22:%5C%22Antennes__HdF_EnService_Agreg%5C%22,%5C%22title%5C%22:%5C%22Antennes_test%5C%22%7D

2. Cliquer sur "partager"
3. Récupérer le lien
4 Ouvrir le lien de partage
5. Voir l'erreur dans la console :

```
Uncaught TypeError: Cannot read properties of undefined (reading 'get')
    at mviewer.js:1345:39
    at Array.forEach (<anonymous>)
    at _setVisibleOverLayers (mviewer.js:1313:16)
    at _applyPermalink (mviewer.js:111:13)
    at Object._overLayersReady [as overLayersReady] (mviewer.js:89:9)
```

2022-11-28 14:18 UTC, Gaetanbrl requested changes
Corriger l'ouverture d'un lien partagé à partir d'une carte comprenant  dans l'URL le paramètre addLayers

2022-11-29 13:11 UTC, dds2010 commented
> Je pense que c'est une feature non prévue. (@dds2010 tu confirmes ?).

Oui je confirme, les impacts sur la fonction de partage n'avait pas été vu et nous prévus dans la demande du coup.

2022-11-29 13:13 UTC, dds2010 commented
> Mais les couches rajoutées ne semble pas conservées lors du partage. Ce point peut être une évolution, ca ne me semble pas bloquant.
> 
> Je remarque par contre qu'on a un bug si on partage une carte qui contient dans l'URL une config json.
> 
>     1. Ouvrir :
> 
> 
> https://dds2010.github.io/mviewer/?config=demo/addlayers.xml&addLayer=%7B%5C%22url%5C%22:%5C%22https://www.geo2france.fr/geoserver/hdf_common/ows%5C%22,%5C%22name%5C%22:%5C%22Antennes__HdF_EnService_Agreg%5C%22,%5C%22title%5C%22:%5C%22Antennes_test%5C%22%7D
> 
>     2. Cliquer sur "partager"
> 
>     3. Récupérer le lien
>        4 Ouvrir le lien de partage
> 
>     4. Voir l'erreur dans la console :

Effectivement dans le lien de partage il y a une référence à une couche qui n'existe pas dans le contexte du coup, je regarde ce que je peux faire pour éviter le plantage

2022-11-29 13:15 UTC, dds2010 commented
> je comprend, le soucis c'est que ca génère une régression sur la fonction de partage pour l'utilisateur qui ajoute ce paramètre dans l'URL

Oui bien sur, je vais traiter la régression.

2022-11-29 13:38 UTC, Gaetanbrl commented
> Oui bien sur, je vais traiter la régression.

Super merci @dds2010 :)

2022-11-30 08:13 UTC, dds2010 commented
> Par contre je comprend pas ce que sont les carrés à l'interrogation d'un CSW (à droite) :

les petits carrés devraient contenir les imagettes, c'est qu'il y a eu un problème de chargement des images. Dans ton cas, je pense que les imagettes référencées dans les métadonnées sont en 404. 

<img width="1750" alt="image" src="https://user-images.githubusercontent.com/438284/204742234-36dc4770-7cc7-4274-b20f-0527ff6789e0.png">

2022-11-30 08:28 UTC, dds2010 commented
> Corriger l'ouverture d'un lien partagé à partir d'une carte comprenant dans l'URL le paramètre addLayers

ok j'ai corrigé ça et refait un merge avec develop pour régler les nouveaux conflits

2022-11-30 08:33 UTC, Gaetanbrl commented
@dds2010 merci pour les modifications, je testerai dans la journée.

2022-12-01 11:48 UTC, Gaetanbrl commented
memo pour autre évol suite à cette PR : 

**Utiliser le fichier .env et non un fichier dans data**

2022-12-01 11:58 UTC, Gaetanbrl commented
Testé : 

1. Ajout d'un nouveau service ==> OK
https://kartenn.region-bretagne.fr/ws/cadastre/france.wms

2. Ajout d'une couche d'un nouveau service ==> Couche `Cadastre complet` ==> OK
3. Ajout dans l'URL de la couche `Cadastre complet`  ==> OK
```
?config=demo/addlayers.xml&addLayer={\"url\":\"https://kartenn.region-bretagne.fr/ws/cadastre/france.wms\",\"name\":\"AMORCES_CAD,LIEUDIT,CP.CadastralParcel,SUBFISCAL,CLOTURE,DETAIL_TOPO,HYDRO,VOIE_COMMUNICATION,BU.Building,BORNE_REPERE\",\"title\":\"DGFIP\"}
```

2022-12-01 13:32 UTC, Gaetanbrl commented
Après relecture de mon test je me demande si ce n'est pas spécifique à la couche cadastre qui utilise un système de virgule dans l'ID  :

`<layer id="AMORCES_CAD,LIEUDIT,CP.CadastralParcel,SUBFISCAL,CLOTURE,DETAIL_TOPO,HYDRO,VOIE_COMMUNICATION,BU.Building,BORNE_REPERE"`

2022-12-01 14:05 UTC, Gaetanbrl commented
Autre test réalisé : 

0. Accès à la démo 

> /?config=demo/addlayers.xml

2. Sélection du service ==> OK
> https://www.geo2france.fr/geoserver/hdf_common/ows

3. Ajout d'une couche d'un nouveau service ==> Couche `aire d’attraction des villes` ==> OK

4. Partage de la carte ==> KO

Erreur :

>Couche(s) aires_attraction_villes* non disponible(s)

2022-12-07 13:22 UTC, Gaetanbrl commented
@dds2010 @vfabry ?

2022-12-07 15:54 UTC, dds2010 commented
> @dds2010 @vfabry ?

Oui pour moi c est hors cadre de cette PR. Je serais plus pour clôturer et merger celle ci qui cours depuis plusieurs mois quitte à ouvrir un autre ticket et une autre PR.

2022-12-08 09:51 UTC, vfabry commented
Effectivement ce n'était pas prévu dans la commande initiale. On pourrait imaginer de financer dette fonctionnalité l'année prochaine.

2022-12-08 10:01 UTC, Gaetanbrl commented
ok @spelhate @lecault @bchartier on peut merger en l'état ?

2022-12-09 16:14 UTC, lecault commented
Bonjour,

Voici mes remarques : 

1. Lorsqu'on enlève une couche de la carte, le symbole qui dit que la couche est sur la carte est toujours présent dans la recherche
![image](https://user-images.githubusercontent.com/5269430/206740110-cedb2a6c-2c4f-493c-a2b6-4cbfa9fd7ae0.png)

=> Problème mineur

2. J'ai un problème **d'affichage d'une donnée ajoutée via CSW provenant de GéoBretagne ou de la Région Bretagne**. Ce problème est du à la façon dont l'URL WMS est renseignée dans nos fiches de métadonnées. En effet, on y met un lien vers le GetCapabilities. Exemple d'URL : https://ows.region-bretagne.fr/geoserver/rb/wms?SERVICE=WMS&REQUEST=GetCapabilities&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetLegendGraphic&SLD_VERSION=1.1.0&FORMAT=image/png&WIDTH=30&HEIGHT=20&LEGEND_OPTIONS=fontName%3AOpen%20Sans%3BfontAntiAliasing%3Atrue%3BfontColor%3A0x777777%3BfontSize%3A10%3Bdpi%3A96&TRANSPARENT=true&LAYER=batiment_region_accessibilite&STYLE=&scale=2183915.0938621783

=>Je ne sais pas si moyen de nettoyer les URLs avant chargement ?

3. J'ai des messages comme ci-dessous sur certains mots clés pour le catalogue de Géo2France
![image](https://user-images.githubusercontent.com/5269430/206741832-e92f963b-d4f7-46ad-b7bf-c92bb2f2c730.png)

=>Je ne comprends pas ces erreurs

Sinon j'ai remarqué le soucis précédent sur le loadbalancer sur geo2france mais pas ailleurs…

2022-12-12 10:03 UTC, pierrejego commented
Hello, je pense que la PR peut être mergée en l'état et faire des nouvelles issues pour le reste des fonctionnalités. Vous en pensez quoi ?

2022-12-12 10:21 UTC, Gaetanbrl commented
> Hello, je pense que la PR peut être mergée en l'état et faire des nouvelles issues pour le reste des fonctionnalités. Vous en pensez quoi ?

ok pour moi.
@lecault ?

2022-12-12 16:50 UTC, lecault commented
OK dac ça sera juste pas déployable chez nous.

2022-12-12 17:09 UTC, Gaetanbrl commented
> OK dac ça sera juste pas déployable chez nous.

Pourquoi ?

2022-12-12 17:11 UTC, Gaetanbrl commented
@lecault l'idée est de faire les modifications dans un second temps, donc c'est vrai que pour le moment ce sera pas déployable car vous avez une spécificité GéoBretagne qu'on ne peut pas imposer aux contributeurs.
Mais on va ouvrir une issue directement après et on portera ensuite les modifications pour que vous puissiez l'utiliser :)

2022-12-12 17:12 UTC, lecault commented
ça ne fonctionne pas avec notre catalogue du à notre façon de saisir les urls

2022-12-13 10:10 UTC, merged

2022-12-13 10:10 UTC, Gaetanbrl commented
merci @dds2010 et @vfabry pour cette contribution.